
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple AWS Lambda application with CRUD operations.

Resources:
  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/createItem.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Events:
        CreateItem:
          Type: Api
          Properties:
            Path: /items
            Method: post

  ReadItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/readItem.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Events:
        ReadItem:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: get

  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/updateItem.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Events:
        UpdateItem:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: put

  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/deleteItem.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Events:
        DeleteItem:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: delete
