
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple AWS Lambda CRUD application using Node.js and middleware functions.

Globals:
  Function:
    Timeout: 10

Resources:
  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/createItem.handler
      Runtime: nodejs14.x
      CodeUri: ./src
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /items
            Method: post

  ReadItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/readItem.handler
      Runtime: nodejs14.x
      CodeUri: ./src
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: get

  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/updateItem.handler
      Runtime: nodejs14.x
      CodeUri: ./src
      Events:
        HttpPut:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: put

  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/deleteItem.handler
      Runtime: nodejs14.x
      CodeUri: ./src
      Events:
        HttpDelete:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: delete
