version = 0.1
[default.deploy.parameters]
stack_name = "aws-sam-lambda-lambda-app-one"
resolve_s3 = true
s3_prefix = "aws-sam-lambda-lambda-app-one"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
