AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # Caller Lambda
  CallerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: callerLambda.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          BACKGROUND_LAMBDA_ARN: !GetAtt BackgroundLambda.Arn
      Policies:
        # Use SAM's built-in policy template to allow invoking the second Lambda
        - LambdaInvokePolicy:
            FunctionName: !GetAtt BackgroundLambda.Arn

  # Background Lambda
  BackgroundLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: backgroundLambda.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 30
